services:
    app:
        container_name: frontend_challenge
        command: sh -c "yarn dev"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
